packages:
  - services/accounting
  - services/whatsapp-agent
allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  core-js: false
  esbuild: true
  msw: true
  node: set this to true or false
  sharp: true
