-- Complements the local sales advances migration. Do not edit the original
-- migration: this file is safe to apply after it in every environment.

ALTER TABLE public.sales_advances
  ADD COLUMN IF NOT EXISTS credit_application_id uuid
    REFERENCES public.customer_credit_applications(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS issue_idempotency_key uuid NOT NULL DEFAULT gen_random_uuid(),
  ADD COLUMN IF NOT EXISTS settlement_idempotency_key uuid NOT NULL DEFAULT gen_random_uuid(),
  ADD COLUMN IF NOT EXISTS fiscal_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.sales_advances
  DROP CONSTRAINT IF EXISTS sales_advances_status_check;

ALTER TABLE public.sales_advances
  ADD CONSTRAINT sales_advances_status_check CHECK (status IN (
    'DRAFT', 'ISSUE_SUBMITTED', 'INVOICED', 'PAID', 'CLOSING',
    'FINAL_INVOICED', 'CREDIT_NOTE_SUBMITTED', 'CREDIT_AVAILABLE',
    'CREDIT_APPLIED', 'SETTLED', 'RECONCILIATION_REQUIRED',
    'FAILED_RECOVERABLE',
    -- Legacy values are retained so already-created local rows remain readable.
    'PENDING_ISSUANCE', 'SETTLEMENT_PENDING', 'SETTLEMENT_IN_PROGRESS',
    'ISSUANCE_ERROR', 'SETTLEMENT_ERROR'
  ));

CREATE UNIQUE INDEX IF NOT EXISTS sales_advances_credit_application_unique
  ON public.sales_advances(credit_application_id)
  WHERE credit_application_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS sales_advances_issue_idempotency_unique
  ON public.sales_advances(issue_idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS sales_advances_settlement_idempotency_unique
  ON public.sales_advances(settlement_idempotency_key);

-- Keep table access aligned with the existing role model instead of allowing
-- every organization member to alter fiscal state.
CREATE OR REPLACE FUNCTION public.can_manage_sales_advance(p_organization_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.organization_members om
    LEFT JOIN public.role_permissions rp ON rp.role_id = om.role_id
    LEFT JOIN public.permissions p ON p.id = rp.permission_id
    WHERE om.organization_id = p_organization_id
      AND om.user_id = auth.uid()
      AND om.is_active = true
      AND (
        om.is_owner = true OR p.key IN (
          'organization.admin', 'sales.manage', 'sales.manage.all',
          'creditnotes.manage', 'collections.manage'
        )
      )
  );
$$;

DROP POLICY IF EXISTS "sales_advances organization members can write" ON public.sales_advances;
CREATE POLICY "sales_advances authorized managers can write"
  ON public.sales_advances FOR ALL
  USING (public.can_manage_sales_advance(organization_id))
  WITH CHECK (public.can_manage_sales_advance(organization_id));

-- An ADVANCE is a fiscal document only. It may be confirmed so the existing
-- ARCA emitter can authorize it, but can never enter any operational flow.
CREATE OR REPLACE FUNCTION public.reject_advance_operational_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.document_type = 'ADVANCE' THEN
    IF NEW.remittance_number IS NOT NULL
      OR NEW.remittance_pdf_url IS NOT NULL
      OR NEW.status IN ('DISPATCH', 'DELIVERED') THEN
      RAISE EXCEPTION 'Las ventas documentales de anticipo no pueden reservar, despachar, entregar ni generar remitos';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.reject_advance_product_items()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_document_type text;
BEGIN
  SELECT document_type INTO v_document_type
  FROM public.sales_orders WHERE id = NEW.sales_order_id;

  IF v_document_type = 'ADVANCE'
    AND (NEW.product_id IS NOT NULL OR NEW.product_variant_id IS NOT NULL) THEN
    RAISE EXCEPTION 'El comprobante de anticipo no puede contener productos ni variantes';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reject_advance_product_items ON public.sales_order_items;
CREATE TRIGGER reject_advance_product_items
  BEFORE INSERT OR UPDATE ON public.sales_order_items
  FOR EACH ROW EXECUTE FUNCTION public.reject_advance_product_items();

-- Applies the fiscal credit generated by the authorized advance NC to the
-- final receivable as one transaction. This intentionally creates no cash
-- payment: customer_credit_applications is the account-current movement.
CREATE OR REPLACE FUNCTION public.apply_sales_advance_credit(p_advance_id uuid)
RETURNS TABLE (
  application_id uuid,
  applied_amount numeric,
  pending_balance numeric,
  advance_status text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_advance public.sales_advances%ROWTYPE;
  v_credit public.customer_credits%ROWTYPE;
  v_receivable public.accounts_receivable%ROWTYPE;
  v_credit_note record;
  v_application_id uuid;
  v_amount numeric(14,2);
  v_next_pending numeric(14,2);
  v_next_credit numeric(14,2);
  v_next_status text;
BEGIN
  SELECT * INTO v_advance
  FROM public.sales_advances
  WHERE id = p_advance_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Anticipo no encontrado';
  END IF;

  IF NOT public.can_manage_sales_advance(v_advance.organization_id) THEN
    RAISE EXCEPTION 'No tenés permisos para aplicar créditos de anticipos';
  END IF;

  IF v_advance.credit_application_id IS NOT NULL THEN
    SELECT amount, account_receivable_id INTO v_amount, v_application_id
    FROM public.customer_credit_applications
    WHERE id = v_advance.credit_application_id;
    SELECT ar.pending_balance INTO v_next_pending
    FROM public.accounts_receivable ar WHERE ar.id = v_advance.final_receivable_id;
    RETURN QUERY SELECT v_advance.credit_application_id, v_amount, v_next_pending, v_advance.status;
    RETURN;
  END IF;

  IF v_advance.customer_credit_id IS NULL OR v_advance.final_receivable_id IS NULL
    OR v_advance.credit_note_id IS NULL THEN
    RAISE EXCEPTION 'El anticipo no tiene crédito, NC o cuenta final listos para aplicar';
  END IF;

  SELECT arca_status, customer_id INTO v_credit_note
  FROM public.credit_notes
  WHERE id = v_advance.credit_note_id
    AND organization_id = v_advance.organization_id
  FOR UPDATE;
  IF NOT FOUND OR v_credit_note.arca_status <> 'authorized' THEN
    RAISE EXCEPTION 'La nota de crédito del anticipo debe estar autorizada por ARCA';
  END IF;

  SELECT * INTO v_credit FROM public.customer_credits
  WHERE id = v_advance.customer_credit_id
    AND organization_id = v_advance.organization_id
  FOR UPDATE;
  SELECT * INTO v_receivable FROM public.accounts_receivable
  WHERE id = v_advance.final_receivable_id
    AND organization_id = v_advance.organization_id
  FOR UPDATE;

  IF NOT FOUND OR v_credit.customer_id <> v_receivable.customer_id
    OR v_credit.customer_id <> v_credit_note.customer_id THEN
    RAISE EXCEPTION 'El crédito, la nota de crédito y la cuenta final deben pertenecer al mismo cliente';
  END IF;

  v_amount := LEAST(v_advance.amount, v_credit.remaining_amount, v_receivable.pending_balance);
  IF v_amount <> v_advance.amount THEN
    RAISE EXCEPTION 'El crédito disponible o el saldo final no coinciden exactamente con el anticipo';
  END IF;

  v_next_credit := round(v_credit.remaining_amount - v_amount, 2);
  v_next_pending := round(v_receivable.pending_balance - v_amount, 2);
  v_next_status := CASE
    WHEN v_next_pending <= 0 THEN 'PAID'
    WHEN v_next_pending < v_receivable.total_amount THEN 'PARTIALLY_PAID'
    ELSE 'PENDING'
  END;

  INSERT INTO public.customer_credit_applications (
    organization_id, customer_id, customer_credit_id, account_receivable_id,
    amount, payment_date, notes
  ) VALUES (
    v_advance.organization_id, v_credit.customer_id, v_credit.id, v_receivable.id,
    v_amount, CURRENT_DATE, 'Aplicación dirigida de anticipo ' || v_advance.id
  ) RETURNING id INTO v_application_id;

  UPDATE public.customer_credits
  SET remaining_amount = v_next_credit
  WHERE id = v_credit.id;
  UPDATE public.accounts_receivable
  SET pending_balance = GREATEST(v_next_pending, 0), status = v_next_status
  WHERE id = v_receivable.id;
  UPDATE public.sales_advances
  SET credit_application_id = v_application_id,
      status = CASE WHEN v_next_pending <= 0 THEN 'SETTLED' ELSE 'CREDIT_APPLIED' END,
      settled_at = CASE WHEN v_next_pending <= 0 THEN now() ELSE NULL END,
      updated_at = now(), last_error = NULL
  WHERE id = v_advance.id;

  RETURN QUERY SELECT v_application_id, v_amount, GREATEST(v_next_pending, 0),
    CASE WHEN v_next_pending <= 0 THEN 'SETTLED' ELSE 'CREDIT_APPLIED' END;
END;
$$;

REVOKE ALL ON FUNCTION public.apply_sales_advance_credit(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_sales_advance_credit(uuid) TO authenticated;
